// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using opytuvannia_backend.Database;

#nullable disable

namespace opytuvannia_backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240504115723_Seed")]
    partial class Seed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("opytuvannia_backend.Entities.Answer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("QuestionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_id");

                    b.HasKey("Id")
                        .HasName("pk_answers");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_answers_question_id");

                    b.ToTable("answers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "fa6616df-1ea8-4dc7-87a6-a97bcffd9608",
                            Content = "Відповідь 88",
                            QuestionId = "d94492ca-4cea-411b-94ca-669b723bd426"
                        },
                        new
                        {
                            Id = "4329f923-e9da-4ad5-9b86-a7aaa7a66ee9",
                            Content = "Відповідь 75",
                            QuestionId = "d94492ca-4cea-411b-94ca-669b723bd426"
                        },
                        new
                        {
                            Id = "8aafa6f4-c0b1-4ef3-8df4-3ff53f246e5d",
                            Content = "Відповідь 82",
                            QuestionId = "d94492ca-4cea-411b-94ca-669b723bd426"
                        },
                        new
                        {
                            Id = "34b9a264-42d8-42b1-9a95-f19daa8ff998",
                            Content = "Відповідь 67",
                            QuestionId = "d94492ca-4cea-411b-94ca-669b723bd426"
                        },
                        new
                        {
                            Id = "d31cea73-ac82-4523-98c6-2b904cc70b40",
                            Content = "Відповідь 92",
                            QuestionId = "f846dae9-d25b-496b-85bf-7683b2e0e7cc"
                        },
                        new
                        {
                            Id = "9d20d6c7-9673-4205-9fa6-3044a2bb60c7",
                            Content = "Відповідь 15",
                            QuestionId = "f846dae9-d25b-496b-85bf-7683b2e0e7cc"
                        },
                        new
                        {
                            Id = "6529135e-1ff3-44f1-aaff-6f4111465faa",
                            Content = "Відповідь 28",
                            QuestionId = "f846dae9-d25b-496b-85bf-7683b2e0e7cc"
                        },
                        new
                        {
                            Id = "98e3ecf8-ae15-428a-89ff-954b9e97168e",
                            Content = "Відповідь 17",
                            QuestionId = "f846dae9-d25b-496b-85bf-7683b2e0e7cc"
                        },
                        new
                        {
                            Id = "9ac5e8c4-e71c-43a0-8195-23e03a721901",
                            Content = "Відповідь 5",
                            QuestionId = "b7f124bc-d583-4320-bd8c-186d57973a84"
                        },
                        new
                        {
                            Id = "1fae2821-d7ec-4376-be5f-52afaa42d23b",
                            Content = "Відповідь 28",
                            QuestionId = "b7f124bc-d583-4320-bd8c-186d57973a84"
                        },
                        new
                        {
                            Id = "e7003155-7495-4c38-8f1c-8f111b0fc979",
                            Content = "Відповідь 42",
                            QuestionId = "b7f124bc-d583-4320-bd8c-186d57973a84"
                        },
                        new
                        {
                            Id = "c9e2b69f-a8aa-4aeb-a3bf-b612a9908db8",
                            Content = "Відповідь 49",
                            QuestionId = "b7f124bc-d583-4320-bd8c-186d57973a84"
                        },
                        new
                        {
                            Id = "23e6e7b3-7d88-4fc9-88e6-d013373bb8ec",
                            Content = "Відповідь 44",
                            QuestionId = "16c428ac-43d2-4396-9c2d-ee2e1e946073"
                        },
                        new
                        {
                            Id = "d7b22c38-79a7-49c6-be50-7faeca776c3f",
                            Content = "Відповідь 29",
                            QuestionId = "16c428ac-43d2-4396-9c2d-ee2e1e946073"
                        },
                        new
                        {
                            Id = "58ba565e-ea3a-459d-8f75-0e9e1ae39e6d",
                            Content = "Відповідь 76",
                            QuestionId = "16c428ac-43d2-4396-9c2d-ee2e1e946073"
                        },
                        new
                        {
                            Id = "94d5ebcf-c567-4f72-a199-95f12a4bb592",
                            Content = "Відповідь 32",
                            QuestionId = "16c428ac-43d2-4396-9c2d-ee2e1e946073"
                        },
                        new
                        {
                            Id = "b9c73822-03f6-42c0-8f9c-205776ae892b",
                            Content = "Відповідь 32",
                            QuestionId = "caa62caf-160e-4ddc-8628-d144637c731e"
                        },
                        new
                        {
                            Id = "5ff93ade-dfb5-437a-8739-d6e778b73fc7",
                            Content = "Відповідь 66",
                            QuestionId = "caa62caf-160e-4ddc-8628-d144637c731e"
                        },
                        new
                        {
                            Id = "3325ea8e-409c-4f73-a051-56dd5f226d66",
                            Content = "Відповідь 4",
                            QuestionId = "caa62caf-160e-4ddc-8628-d144637c731e"
                        },
                        new
                        {
                            Id = "99cbd3ff-5f13-472e-968e-9860be79055e",
                            Content = "Відповідь 70",
                            QuestionId = "caa62caf-160e-4ddc-8628-d144637c731e"
                        },
                        new
                        {
                            Id = "663bde69-3663-448b-a357-f11ed086266a",
                            Content = "Відповідь 20",
                            QuestionId = "c43dbe6d-5571-448b-af78-58a68529c8c5"
                        },
                        new
                        {
                            Id = "24d06306-e402-4bd7-a853-155bbcf2992b",
                            Content = "Відповідь 33",
                            QuestionId = "c43dbe6d-5571-448b-af78-58a68529c8c5"
                        },
                        new
                        {
                            Id = "0b264823-305f-471d-9d7e-92e3fc9b937d",
                            Content = "Відповідь 31",
                            QuestionId = "c43dbe6d-5571-448b-af78-58a68529c8c5"
                        },
                        new
                        {
                            Id = "884b0b2a-fca6-4ec7-9eb4-f5c82ec17465",
                            Content = "Відповідь 64",
                            QuestionId = "c43dbe6d-5571-448b-af78-58a68529c8c5"
                        },
                        new
                        {
                            Id = "4df47b6d-cab5-4ae4-bd40-7dccd18efda2",
                            Content = "Відповідь 97",
                            QuestionId = "fae45801-2c7a-47ae-88f0-9998116409cb"
                        },
                        new
                        {
                            Id = "0a07d221-6866-4674-abc3-f3390aa7345a",
                            Content = "Відповідь 95",
                            QuestionId = "fae45801-2c7a-47ae-88f0-9998116409cb"
                        },
                        new
                        {
                            Id = "1e93ad94-c71e-4f4e-b352-efccce5b2467",
                            Content = "Відповідь 85",
                            QuestionId = "fae45801-2c7a-47ae-88f0-9998116409cb"
                        },
                        new
                        {
                            Id = "376555f6-395e-4b8a-a6b2-2e22ced7ac2a",
                            Content = "Відповідь 19",
                            QuestionId = "fae45801-2c7a-47ae-88f0-9998116409cb"
                        },
                        new
                        {
                            Id = "f4e4ae6b-b8d3-4d4e-add9-99214dddea14",
                            Content = "Відповідь 70",
                            QuestionId = "cf9cbbdd-b0d4-4249-a600-8073451054e5"
                        },
                        new
                        {
                            Id = "f467201b-655b-44bf-a2f1-930e02e8ec4c",
                            Content = "Відповідь 71",
                            QuestionId = "cf9cbbdd-b0d4-4249-a600-8073451054e5"
                        },
                        new
                        {
                            Id = "71bfa9ac-d166-49a2-b169-392ce8a7c0f2",
                            Content = "Відповідь 36",
                            QuestionId = "cf9cbbdd-b0d4-4249-a600-8073451054e5"
                        },
                        new
                        {
                            Id = "a09cc590-95e8-4261-94aa-bf5d9e62074b",
                            Content = "Відповідь 52",
                            QuestionId = "cf9cbbdd-b0d4-4249-a600-8073451054e5"
                        },
                        new
                        {
                            Id = "355bac16-3086-4403-955c-6910e31de947",
                            Content = "Відповідь 91",
                            QuestionId = "2bb4699a-d432-4e51-bdd8-24f0089d5d3d"
                        },
                        new
                        {
                            Id = "fe03062b-4efc-437d-9aeb-e73cd0ab702f",
                            Content = "Відповідь 96",
                            QuestionId = "2bb4699a-d432-4e51-bdd8-24f0089d5d3d"
                        },
                        new
                        {
                            Id = "d02ae9fd-9f19-44e1-96a7-5a52056edd84",
                            Content = "Відповідь 69",
                            QuestionId = "2bb4699a-d432-4e51-bdd8-24f0089d5d3d"
                        },
                        new
                        {
                            Id = "5c0349dd-7445-4162-839b-62dcff8a3567",
                            Content = "Відповідь 6",
                            QuestionId = "2bb4699a-d432-4e51-bdd8-24f0089d5d3d"
                        },
                        new
                        {
                            Id = "a251f768-51be-4d0c-9498-5f4472199718",
                            Content = "Відповідь 78",
                            QuestionId = "6afd4273-4755-4a70-8452-ed2e79652000"
                        },
                        new
                        {
                            Id = "eb8d6dc5-58d5-4b15-ab71-f31bec15ba91",
                            Content = "Відповідь 78",
                            QuestionId = "6afd4273-4755-4a70-8452-ed2e79652000"
                        },
                        new
                        {
                            Id = "b4daa7eb-dc8f-4a52-b369-207cf2050148",
                            Content = "Відповідь 25",
                            QuestionId = "6afd4273-4755-4a70-8452-ed2e79652000"
                        },
                        new
                        {
                            Id = "ceb349a6-2382-4291-b7f4-5f4a4e62ae66",
                            Content = "Відповідь 54",
                            QuestionId = "6afd4273-4755-4a70-8452-ed2e79652000"
                        },
                        new
                        {
                            Id = "0b0cffbd-4f4a-432e-a66f-7d1f140738b6",
                            Content = "Відповідь 28",
                            QuestionId = "b781678a-de34-458b-a5d2-1e23d86a6484"
                        },
                        new
                        {
                            Id = "a6a99e86-479b-4cee-b7a5-1dde34f794cd",
                            Content = "Відповідь 50",
                            QuestionId = "b781678a-de34-458b-a5d2-1e23d86a6484"
                        },
                        new
                        {
                            Id = "7c725aeb-38b1-4ae9-8bbe-972e3d061cee",
                            Content = "Відповідь 29",
                            QuestionId = "b781678a-de34-458b-a5d2-1e23d86a6484"
                        },
                        new
                        {
                            Id = "a21ffd18-e7b0-4e12-9810-d21e58995219",
                            Content = "Відповідь 1",
                            QuestionId = "b781678a-de34-458b-a5d2-1e23d86a6484"
                        },
                        new
                        {
                            Id = "96ece23f-7386-4481-bb84-1df72cb1c0bb",
                            Content = "Відповідь 4",
                            QuestionId = "047902f0-b550-4fa5-a260-feff9279373f"
                        },
                        new
                        {
                            Id = "39aca928-10e4-4ec0-b756-54f036e20a95",
                            Content = "Відповідь 30",
                            QuestionId = "047902f0-b550-4fa5-a260-feff9279373f"
                        },
                        new
                        {
                            Id = "862378db-6659-4641-a13b-b0adffa97502",
                            Content = "Відповідь 78",
                            QuestionId = "047902f0-b550-4fa5-a260-feff9279373f"
                        },
                        new
                        {
                            Id = "a196258d-afd3-458d-9692-a40d7ffe3491",
                            Content = "Відповідь 57",
                            QuestionId = "047902f0-b550-4fa5-a260-feff9279373f"
                        },
                        new
                        {
                            Id = "88b748f2-da29-4ecf-a9d7-58c5fcd7da48",
                            Content = "Відповідь 75",
                            QuestionId = "0edc0aab-65bc-4998-95d7-859c5e751c98"
                        },
                        new
                        {
                            Id = "a95cdeef-c11f-4f5d-a374-96db6c1492a2",
                            Content = "Відповідь 27",
                            QuestionId = "0edc0aab-65bc-4998-95d7-859c5e751c98"
                        },
                        new
                        {
                            Id = "c3a7ad63-fa27-4210-b1ef-d1e487f2f642",
                            Content = "Відповідь 60",
                            QuestionId = "0edc0aab-65bc-4998-95d7-859c5e751c98"
                        },
                        new
                        {
                            Id = "f8e41b46-3c54-4ae0-a3ad-0f9b9ed7e73f",
                            Content = "Відповідь 62",
                            QuestionId = "0edc0aab-65bc-4998-95d7-859c5e751c98"
                        },
                        new
                        {
                            Id = "7385d718-4619-44a6-a458-5a792ff084df",
                            Content = "Відповідь 72",
                            QuestionId = "7b49c63d-379f-47bb-bb8a-8afa2586c8eb"
                        },
                        new
                        {
                            Id = "1a3d4422-13b4-41c1-8d52-4f70d00f2648",
                            Content = "Відповідь 10",
                            QuestionId = "7b49c63d-379f-47bb-bb8a-8afa2586c8eb"
                        },
                        new
                        {
                            Id = "40d66e60-1664-43fa-a4c3-ce3deb7af848",
                            Content = "Відповідь 20",
                            QuestionId = "7b49c63d-379f-47bb-bb8a-8afa2586c8eb"
                        },
                        new
                        {
                            Id = "d75e5721-c293-4e84-9db5-ed95de65cc5c",
                            Content = "Відповідь 58",
                            QuestionId = "7b49c63d-379f-47bb-bb8a-8afa2586c8eb"
                        },
                        new
                        {
                            Id = "686e8897-ea89-4b5f-9317-a6cf508f01d9",
                            Content = "Відповідь 88",
                            QuestionId = "2191f4e8-a7ba-45e3-8d41-da61ef25b873"
                        },
                        new
                        {
                            Id = "81ba4a7f-a913-4f34-9e1b-b95056a7e4a2",
                            Content = "Відповідь 89",
                            QuestionId = "2191f4e8-a7ba-45e3-8d41-da61ef25b873"
                        },
                        new
                        {
                            Id = "f72d5210-614b-4da9-8fca-83ea5d3126a9",
                            Content = "Відповідь 5",
                            QuestionId = "2191f4e8-a7ba-45e3-8d41-da61ef25b873"
                        },
                        new
                        {
                            Id = "52635b69-8da4-4d44-8d13-46613c43bb43",
                            Content = "Відповідь 38",
                            QuestionId = "2191f4e8-a7ba-45e3-8d41-da61ef25b873"
                        },
                        new
                        {
                            Id = "6a7469cb-79c5-42d4-af7e-eac1528c5b58",
                            Content = "Відповідь 89",
                            QuestionId = "c9baf7e5-ebb9-4498-adc7-6e87990d2636"
                        },
                        new
                        {
                            Id = "5556316a-b00f-4843-84a3-4060a4f33e7f",
                            Content = "Відповідь 54",
                            QuestionId = "c9baf7e5-ebb9-4498-adc7-6e87990d2636"
                        },
                        new
                        {
                            Id = "1d93ade1-13b1-40c8-9731-542307d4ef56",
                            Content = "Відповідь 39",
                            QuestionId = "c9baf7e5-ebb9-4498-adc7-6e87990d2636"
                        },
                        new
                        {
                            Id = "10e3f030-53e2-42d3-8fce-d943d1c3a276",
                            Content = "Відповідь 18",
                            QuestionId = "c9baf7e5-ebb9-4498-adc7-6e87990d2636"
                        });
                });

            modelBuilder.Entity("opytuvannia_backend.Entities.Company", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("LogoSrc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("logo_src");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_companies");

                    b.ToTable("companies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "d56e3b51-f341-49f6-b803-0fb8494e01d0",
                            LogoSrc = "https://silpo.ua/images/silpo_fb_share.png",
                            Name = "Сільпо"
                        },
                        new
                        {
                            Id = "729e7118-9994-4318-9ca0-84a3d3ff3a67",
                            LogoSrc = "https://cdn.metro-online.com/-/media/Project/MCW/RU_Metro/2021/join-us/Metro.png?rev=fe69769d14aa4105bc7e5731e32ebfc7&w=339&hash=783A0BB0789E586BB438C44B0778558A",
                            Name = "Metro"
                        },
                        new
                        {
                            Id = "9f18a11d-d392-48e3-87eb-916536aa49d4",
                            LogoSrc = "https://allretail.ua/static/files/originals/2/85/30b01f786bd9a28d98e745247184f852.svg",
                            Name = "АТБ"
                        });
                });

            modelBuilder.Entity("opytuvannia_backend.Entities.Question", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("SurveyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("survey_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_questions");

                    b.HasIndex("SurveyId")
                        .HasDatabaseName("ix_questions_survey_id");

                    b.ToTable("questions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "d94492ca-4cea-411b-94ca-669b723bd426",
                            SurveyId = "66908dd3-7431-4742-b97b-35419aeaf7ad",
                            Title = "Яке пиво ви купуєте найчастіше?"
                        },
                        new
                        {
                            Id = "f846dae9-d25b-496b-85bf-7683b2e0e7cc",
                            SurveyId = "66908dd3-7431-4742-b97b-35419aeaf7ad",
                            Title = "Чи спробували ви нові сорти пива в нашому магазині?"
                        },
                        new
                        {
                            Id = "b7f124bc-d583-4320-bd8c-186d57973a84",
                            SurveyId = "66908dd3-7431-4742-b97b-35419aeaf7ad",
                            Title = "Які характеристики пива важливі для вас?"
                        },
                        new
                        {
                            Id = "16c428ac-43d2-4396-9c2d-ee2e1e946073",
                            SurveyId = "66908dd3-7431-4742-b97b-35419aeaf7ad",
                            Title = "Як часто ви купуєте пиво в наших магазинах?"
                        },
                        new
                        {
                            Id = "caa62caf-160e-4ddc-8628-d144637c731e",
                            SurveyId = "af8ffc99-ab31-4d32-8252-1c27b9756858",
                            Title = "Який продукт ви купуєте найчастіше в Metro?"
                        },
                        new
                        {
                            Id = "c43dbe6d-5571-448b-af78-58a68529c8c5",
                            SurveyId = "af8ffc99-ab31-4d32-8252-1c27b9756858",
                            Title = "Чи задоволені ви асортиментом товарів у наших магазинах?"
                        },
                        new
                        {
                            Id = "fae45801-2c7a-47ae-88f0-9998116409cb",
                            SurveyId = "af8ffc99-ab31-4d32-8252-1c27b9756858",
                            Title = "Які характеристики товарів важливі для вас при покупці?"
                        },
                        new
                        {
                            Id = "cf9cbbdd-b0d4-4249-a600-8073451054e5",
                            SurveyId = "af8ffc99-ab31-4d32-8252-1c27b9756858",
                            Title = "Як часто ви відвідуєте наші магазини?"
                        },
                        new
                        {
                            Id = "2bb4699a-d432-4e51-bdd8-24f0089d5d3d",
                            SurveyId = "2a5c430e-6c91-41a8-840c-745b14c3e430",
                            Title = "Як часто ви здійснюєте покупки в АТБ?"
                        },
                        new
                        {
                            Id = "6afd4273-4755-4a70-8452-ed2e79652000",
                            SurveyId = "2a5c430e-6c91-41a8-840c-745b14c3e430",
                            Title = "Які товари ви найчастіше купуєте в наших магазинах?"
                        },
                        new
                        {
                            Id = "b781678a-de34-458b-a5d2-1e23d86a6484",
                            SurveyId = "2a5c430e-6c91-41a8-840c-745b14c3e430",
                            Title = "Чи задоволені ви якістю обслуговування у наших магазинах?"
                        },
                        new
                        {
                            Id = "047902f0-b550-4fa5-a260-feff9279373f",
                            SurveyId = "2a5c430e-6c91-41a8-840c-745b14c3e430",
                            Title = "Чи вважаєте ви наші ціни конкурентоспроможними?"
                        },
                        new
                        {
                            Id = "0edc0aab-65bc-4998-95d7-859c5e751c98",
                            SurveyId = "c6d37fbc-d07b-40c6-9a84-6214326d753c",
                            Title = "Як ви оцінюєте чистоту наших магазинів?"
                        },
                        new
                        {
                            Id = "7b49c63d-379f-47bb-bb8a-8afa2586c8eb",
                            SurveyId = "c6d37fbc-d07b-40c6-9a84-6214326d753c",
                            Title = "Чи допомагає вам персонал з пошуком товарів?"
                        },
                        new
                        {
                            Id = "2191f4e8-a7ba-45e3-8d41-da61ef25b873",
                            SurveyId = "c6d37fbc-d07b-40c6-9a84-6214326d753c",
                            Title = "Чи вважаєте ви, що у нас завжди є необхідні товари?"
                        },
                        new
                        {
                            Id = "c9baf7e5-ebb9-4498-adc7-6e87990d2636",
                            SurveyId = "c6d37fbc-d07b-40c6-9a84-6214326d753c",
                            Title = "Чи радите ви своїм знайомим відвідувати магазини АТБ?"
                        });
                });

            modelBuilder.Entity("opytuvannia_backend.Entities.Respondent", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birth_date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("Gender")
                        .HasColumnType("character varying(10)")
                        .HasColumnName("gender");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.HasKey("Id")
                        .HasName("pk_respondents");

                    b.ToTable("respondents", (string)null);
                });

            modelBuilder.Entity("opytuvannia_backend.Entities.RespondentSurvey", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CompletionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completion_date");

                    b.Property<string>("RespondentId")
                        .IsRequired()
                        .HasColumnType("character varying(36)")
                        .HasColumnName("respondent_id");

                    b.Property<string>("SurveyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("survey_id");

                    b.HasKey("Id")
                        .HasName("pk_respondent_surveys");

                    b.HasIndex("RespondentId")
                        .HasDatabaseName("ix_respondent_surveys_respondent_id");

                    b.HasIndex("SurveyId")
                        .HasDatabaseName("ix_respondent_surveys_survey_id");

                    b.ToTable("respondent_surveys", (string)null);
                });

            modelBuilder.Entity("opytuvannia_backend.Entities.RespondentSurveyAnswer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AnswerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("answer_id");

                    b.Property<string>("QuestionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_id");

                    b.Property<string>("RespondentSurveyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("respondent_survey_id");

                    b.HasKey("Id")
                        .HasName("pk_respondent_survey_answers");

                    b.HasIndex("AnswerId")
                        .HasDatabaseName("ix_respondent_survey_answers_answer_id");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_respondent_survey_answers_question_id");

                    b.HasIndex("RespondentSurveyId")
                        .HasDatabaseName("ix_respondent_survey_answers_respondent_survey_id");

                    b.ToTable("respondent_survey_answers", (string)null);
                });

            modelBuilder.Entity("opytuvannia_backend.Entities.Survey", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Reward")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reward");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_surveys");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_surveys_company_id");

                    b.ToTable("surveys", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "66908dd3-7431-4742-b97b-35419aeaf7ad",
                            CompanyId = "d56e3b51-f341-49f6-b803-0fb8494e01d0",
                            Description = "Опитування про ваші уподобання щодо пива",
                            Reward = "Промокод -50% на чернігівське титан zxcqw-e13371000-7wwww",
                            Title = "Споживання пива"
                        },
                        new
                        {
                            Id = "af8ffc99-ab31-4d32-8252-1c27b9756858",
                            CompanyId = "729e7118-9994-4318-9ca0-84a3d3ff3a67",
                            Description = "Допоможіть нам визначити найпопулярніший продукт в Metro",
                            Reward = "+100 грн",
                            Title = "Найкращий продукт"
                        },
                        new
                        {
                            Id = "2a5c430e-6c91-41a8-840c-745b14c3e430",
                            CompanyId = "9f18a11d-d392-48e3-87eb-916536aa49d4",
                            Description = "Щоб покращити обслуговування, просимо вас взяти участь в нашому опитуванні",
                            Reward = "Знижка 10% на наступну покупку",
                            Title = "Ваші покупки в АТБ"
                        },
                        new
                        {
                            Id = "c6d37fbc-d07b-40c6-9a84-6214326d753c",
                            CompanyId = "9f18a11d-d392-48e3-87eb-916536aa49d4",
                            Description = "Оцініть якість обслуговування в наших магазинах",
                            Reward = "Безкоштовна доставка при наступному замовленні",
                            Title = "Якість обслуговування"
                        });
                });

            modelBuilder.Entity("opytuvannia_backend.Entities.Answer", b =>
                {
                    b.HasOne("opytuvannia_backend.Entities.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_answers_questions_question_id");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("opytuvannia_backend.Entities.Question", b =>
                {
                    b.HasOne("opytuvannia_backend.Entities.Survey", "Survey")
                        .WithMany("Tasks")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_questions_surveys_survey_id");

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("opytuvannia_backend.Entities.RespondentSurvey", b =>
                {
                    b.HasOne("opytuvannia_backend.Entities.Respondent", "Respondent")
                        .WithMany("CompletedSurveys")
                        .HasForeignKey("RespondentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_respondent_surveys_respondents_respondent_id");

                    b.HasOne("opytuvannia_backend.Entities.Survey", "Survey")
                        .WithMany()
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_respondent_surveys_surveys_survey_id");

                    b.Navigation("Respondent");

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("opytuvannia_backend.Entities.RespondentSurveyAnswer", b =>
                {
                    b.HasOne("opytuvannia_backend.Entities.Answer", "Answer")
                        .WithMany()
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_respondent_survey_answers_answers_answer_id");

                    b.HasOne("opytuvannia_backend.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_respondent_survey_answers_questions_question_id");

                    b.HasOne("opytuvannia_backend.Entities.RespondentSurvey", "RespondentSurvey")
                        .WithMany("Answers")
                        .HasForeignKey("RespondentSurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_respondent_survey_answers_respondent_surveys_respondent_sur");

                    b.Navigation("Answer");

                    b.Navigation("Question");

                    b.Navigation("RespondentSurvey");
                });

            modelBuilder.Entity("opytuvannia_backend.Entities.Survey", b =>
                {
                    b.HasOne("opytuvannia_backend.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_surveys_companies_company_id");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("opytuvannia_backend.Entities.Question", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("opytuvannia_backend.Entities.Respondent", b =>
                {
                    b.Navigation("CompletedSurveys");
                });

            modelBuilder.Entity("opytuvannia_backend.Entities.RespondentSurvey", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("opytuvannia_backend.Entities.Survey", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
