// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using opytuvannia_backend.Database;

#nullable disable

namespace opytuvannia_backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240504174810_AddedRewardEntity")]
    partial class AddedRewardEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("opytuvannia_backend.Entities.Answer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("QuestionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_id");

                    b.HasKey("Id")
                        .HasName("pk_answers");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_answers_question_id");

                    b.ToTable("answers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "a4ae58c7-8b8c-4fd5-95d8-8e1525b94fc2",
                            Content = "Відповідь 50",
                            QuestionId = "6d3d0979-35c7-47e7-ad80-56b5fe36307b"
                        },
                        new
                        {
                            Id = "02d1740d-c0f3-4a38-8338-099b021e25b1",
                            Content = "Відповідь 78",
                            QuestionId = "6d3d0979-35c7-47e7-ad80-56b5fe36307b"
                        },
                        new
                        {
                            Id = "8cc2353b-0c64-4a11-a315-dcc8bc1c487b",
                            Content = "Відповідь 62",
                            QuestionId = "6d3d0979-35c7-47e7-ad80-56b5fe36307b"
                        },
                        new
                        {
                            Id = "2956b1cf-6562-470a-9cb2-5d5af59aa3ac",
                            Content = "Відповідь 40",
                            QuestionId = "6d3d0979-35c7-47e7-ad80-56b5fe36307b"
                        },
                        new
                        {
                            Id = "8368d15c-a9aa-4a54-99c7-91e1a0be6b72",
                            Content = "Відповідь 32",
                            QuestionId = "4c6005ec-2113-45f8-a244-44b46fc41e71"
                        },
                        new
                        {
                            Id = "83f26dff-93c1-43e9-a758-0fdef393d5d5",
                            Content = "Відповідь 34",
                            QuestionId = "4c6005ec-2113-45f8-a244-44b46fc41e71"
                        },
                        new
                        {
                            Id = "3213a5cd-fc99-4b9d-9b28-1e190e13a88f",
                            Content = "Відповідь 49",
                            QuestionId = "4c6005ec-2113-45f8-a244-44b46fc41e71"
                        },
                        new
                        {
                            Id = "e8d12e13-61d1-4c28-be6b-20a5b452631f",
                            Content = "Відповідь 12",
                            QuestionId = "4c6005ec-2113-45f8-a244-44b46fc41e71"
                        },
                        new
                        {
                            Id = "b9b9cdae-2131-497d-b678-4786b5ad00fb",
                            Content = "Відповідь 63",
                            QuestionId = "ab44fa3d-7ab9-41e2-9592-9ea7b99bf39b"
                        },
                        new
                        {
                            Id = "6ab56bac-2016-4752-8ece-f5e66301defe",
                            Content = "Відповідь 22",
                            QuestionId = "ab44fa3d-7ab9-41e2-9592-9ea7b99bf39b"
                        },
                        new
                        {
                            Id = "ff7cc8eb-0122-4967-9fd2-402b56db97a9",
                            Content = "Відповідь 24",
                            QuestionId = "ab44fa3d-7ab9-41e2-9592-9ea7b99bf39b"
                        },
                        new
                        {
                            Id = "77fd9ab9-6d54-4eb1-8970-8a1b8e89c60b",
                            Content = "Відповідь 74",
                            QuestionId = "ab44fa3d-7ab9-41e2-9592-9ea7b99bf39b"
                        },
                        new
                        {
                            Id = "8ac2ab72-2fa8-42ec-a8f6-902e4bacb882",
                            Content = "Відповідь 48",
                            QuestionId = "488e1580-2be8-4224-a479-035586148414"
                        },
                        new
                        {
                            Id = "f9dd026a-c159-4040-8c3b-4995e9ada2af",
                            Content = "Відповідь 58",
                            QuestionId = "488e1580-2be8-4224-a479-035586148414"
                        },
                        new
                        {
                            Id = "c2e77091-974a-4019-8424-39f881314f70",
                            Content = "Відповідь 41",
                            QuestionId = "488e1580-2be8-4224-a479-035586148414"
                        },
                        new
                        {
                            Id = "e2f87636-f079-436f-ae6d-0f5a92539dd7",
                            Content = "Відповідь 70",
                            QuestionId = "488e1580-2be8-4224-a479-035586148414"
                        },
                        new
                        {
                            Id = "1c7a3485-b003-43dc-a7ca-b10731670108",
                            Content = "Відповідь 75",
                            QuestionId = "482e42f4-f116-4b47-b0ae-10b70354755d"
                        },
                        new
                        {
                            Id = "fb381457-622e-4ebe-9d09-26859ae0a806",
                            Content = "Відповідь 96",
                            QuestionId = "482e42f4-f116-4b47-b0ae-10b70354755d"
                        },
                        new
                        {
                            Id = "adab1c34-8076-4e46-b088-3998d44b3f34",
                            Content = "Відповідь 21",
                            QuestionId = "482e42f4-f116-4b47-b0ae-10b70354755d"
                        },
                        new
                        {
                            Id = "891f8a89-a793-41e3-8d75-9f4deea608d6",
                            Content = "Відповідь 50",
                            QuestionId = "482e42f4-f116-4b47-b0ae-10b70354755d"
                        },
                        new
                        {
                            Id = "9f50ab0e-dd5c-4155-ab5d-0b4aba19b911",
                            Content = "Відповідь 92",
                            QuestionId = "c82ae074-05e3-4b6f-8789-e951720658a0"
                        },
                        new
                        {
                            Id = "7507f6d8-8395-4905-9426-853d4b506c53",
                            Content = "Відповідь 38",
                            QuestionId = "c82ae074-05e3-4b6f-8789-e951720658a0"
                        },
                        new
                        {
                            Id = "1f0d7cb1-c83a-4381-88c8-8448ee7b0ad5",
                            Content = "Відповідь 21",
                            QuestionId = "c82ae074-05e3-4b6f-8789-e951720658a0"
                        },
                        new
                        {
                            Id = "2e0cc471-f6e5-4354-bb03-f3e607bfaa8f",
                            Content = "Відповідь 6",
                            QuestionId = "c82ae074-05e3-4b6f-8789-e951720658a0"
                        },
                        new
                        {
                            Id = "1f9d897c-9167-483c-b12b-d932f44d988b",
                            Content = "Відповідь 60",
                            QuestionId = "5aa48f79-3caa-4536-ab92-6675a5ce19cc"
                        },
                        new
                        {
                            Id = "7e878d7b-8d17-4757-a5de-7446e0001743",
                            Content = "Відповідь 87",
                            QuestionId = "5aa48f79-3caa-4536-ab92-6675a5ce19cc"
                        },
                        new
                        {
                            Id = "035b0589-bb77-4677-80f2-4e0d0c07dd9f",
                            Content = "Відповідь 32",
                            QuestionId = "5aa48f79-3caa-4536-ab92-6675a5ce19cc"
                        },
                        new
                        {
                            Id = "5a972830-996b-4d0c-a696-e529db2d1264",
                            Content = "Відповідь 28",
                            QuestionId = "5aa48f79-3caa-4536-ab92-6675a5ce19cc"
                        },
                        new
                        {
                            Id = "3a3c51c6-3d34-4902-bef6-fc2f0c7031ae",
                            Content = "Відповідь 63",
                            QuestionId = "81638814-b787-486a-a9c9-610b8a16d3e1"
                        },
                        new
                        {
                            Id = "df821a9e-97fc-4075-a42a-5c03f4587152",
                            Content = "Відповідь 94",
                            QuestionId = "81638814-b787-486a-a9c9-610b8a16d3e1"
                        },
                        new
                        {
                            Id = "247861f5-b31c-45be-9099-fd40793f60a9",
                            Content = "Відповідь 89",
                            QuestionId = "81638814-b787-486a-a9c9-610b8a16d3e1"
                        },
                        new
                        {
                            Id = "f8c0c73a-9fb3-4b3a-a6ab-10e445820812",
                            Content = "Відповідь 64",
                            QuestionId = "81638814-b787-486a-a9c9-610b8a16d3e1"
                        },
                        new
                        {
                            Id = "31662ed9-4990-4930-9401-eb50813f6d62",
                            Content = "Відповідь 20",
                            QuestionId = "2fec5013-2680-43a6-8621-40d14ec904c0"
                        },
                        new
                        {
                            Id = "041d77e3-11ca-4835-a373-b3f8d6e73ae5",
                            Content = "Відповідь 50",
                            QuestionId = "2fec5013-2680-43a6-8621-40d14ec904c0"
                        },
                        new
                        {
                            Id = "ad851c3c-4317-4a5c-94c5-5fa521d405d8",
                            Content = "Відповідь 36",
                            QuestionId = "2fec5013-2680-43a6-8621-40d14ec904c0"
                        },
                        new
                        {
                            Id = "3fba1b3f-8222-4d9d-947f-1da856ce948c",
                            Content = "Відповідь 19",
                            QuestionId = "2fec5013-2680-43a6-8621-40d14ec904c0"
                        },
                        new
                        {
                            Id = "d66db0c9-2e9a-4ff0-863c-64b44f52c990",
                            Content = "Відповідь 59",
                            QuestionId = "2d6da8e2-dc0b-47e7-962b-b8cd3997eba5"
                        },
                        new
                        {
                            Id = "51ec36b7-1259-45b1-afc4-5b4b94db281d",
                            Content = "Відповідь 83",
                            QuestionId = "2d6da8e2-dc0b-47e7-962b-b8cd3997eba5"
                        },
                        new
                        {
                            Id = "f0e5d721-eced-408a-92cf-3d371daf5412",
                            Content = "Відповідь 83",
                            QuestionId = "2d6da8e2-dc0b-47e7-962b-b8cd3997eba5"
                        },
                        new
                        {
                            Id = "0eee8e4b-de17-4294-b0a2-ce763c90b710",
                            Content = "Відповідь 67",
                            QuestionId = "2d6da8e2-dc0b-47e7-962b-b8cd3997eba5"
                        },
                        new
                        {
                            Id = "d7fe748b-51a3-41b8-be5d-bb7e94767795",
                            Content = "Відповідь 19",
                            QuestionId = "d504962b-d5ef-4d58-af58-606a2c852610"
                        },
                        new
                        {
                            Id = "1a693c72-99c1-4da8-b866-47ad7bf3389a",
                            Content = "Відповідь 14",
                            QuestionId = "d504962b-d5ef-4d58-af58-606a2c852610"
                        },
                        new
                        {
                            Id = "e433759e-1a15-4f13-a476-549581b071de",
                            Content = "Відповідь 83",
                            QuestionId = "d504962b-d5ef-4d58-af58-606a2c852610"
                        },
                        new
                        {
                            Id = "36a4531b-e7e3-4efd-8b8d-94ea6a95a242",
                            Content = "Відповідь 34",
                            QuestionId = "d504962b-d5ef-4d58-af58-606a2c852610"
                        },
                        new
                        {
                            Id = "7ba6bdf7-59b2-4ebf-8818-429cb73b1661",
                            Content = "Відповідь 36",
                            QuestionId = "9dca22e2-4bd9-4a82-882a-f19835c95118"
                        },
                        new
                        {
                            Id = "164034e6-5e6a-4c26-97c2-a7a492cfc342",
                            Content = "Відповідь 44",
                            QuestionId = "9dca22e2-4bd9-4a82-882a-f19835c95118"
                        },
                        new
                        {
                            Id = "02d3824d-1fdc-429f-86d8-b6e8834618b2",
                            Content = "Відповідь 15",
                            QuestionId = "9dca22e2-4bd9-4a82-882a-f19835c95118"
                        },
                        new
                        {
                            Id = "4e1c1d98-fb05-41f9-9e70-cff217e1c787",
                            Content = "Відповідь 87",
                            QuestionId = "9dca22e2-4bd9-4a82-882a-f19835c95118"
                        },
                        new
                        {
                            Id = "3e9e54d6-074d-48f7-bfcf-472f5b2089c2",
                            Content = "Відповідь 3",
                            QuestionId = "c085cd1d-4894-43f8-b383-d17371636f1c"
                        },
                        new
                        {
                            Id = "a8e6c2b9-658f-4058-8be0-775d86d179e1",
                            Content = "Відповідь 8",
                            QuestionId = "c085cd1d-4894-43f8-b383-d17371636f1c"
                        },
                        new
                        {
                            Id = "16dbc31f-bad6-4766-84d2-6cad3a765fb8",
                            Content = "Відповідь 89",
                            QuestionId = "c085cd1d-4894-43f8-b383-d17371636f1c"
                        },
                        new
                        {
                            Id = "ed4e2d0e-8dca-49fe-84f3-3b2244fe67c7",
                            Content = "Відповідь 50",
                            QuestionId = "c085cd1d-4894-43f8-b383-d17371636f1c"
                        },
                        new
                        {
                            Id = "035c7b92-52f7-4956-ae6e-df0ddb90234d",
                            Content = "Відповідь 23",
                            QuestionId = "15e8db4e-bb53-4164-8ac9-0e1e995d2e1f"
                        },
                        new
                        {
                            Id = "3c1bcff9-bede-4bc8-940f-863e7f735634",
                            Content = "Відповідь 65",
                            QuestionId = "15e8db4e-bb53-4164-8ac9-0e1e995d2e1f"
                        },
                        new
                        {
                            Id = "bb06a73a-0cce-49c3-a0d3-503e71ab6855",
                            Content = "Відповідь 48",
                            QuestionId = "15e8db4e-bb53-4164-8ac9-0e1e995d2e1f"
                        },
                        new
                        {
                            Id = "aa96bda8-a222-4223-b724-b906e96a68bc",
                            Content = "Відповідь 73",
                            QuestionId = "15e8db4e-bb53-4164-8ac9-0e1e995d2e1f"
                        },
                        new
                        {
                            Id = "a8096540-834c-4f95-9317-fa5773d3676b",
                            Content = "Відповідь 81",
                            QuestionId = "cb1f165b-2950-481b-91a2-89174acad2b8"
                        },
                        new
                        {
                            Id = "e7c4c6b2-2313-4f24-9c86-2c25e3e22557",
                            Content = "Відповідь 26",
                            QuestionId = "cb1f165b-2950-481b-91a2-89174acad2b8"
                        },
                        new
                        {
                            Id = "a1a1dd31-2700-426b-817b-bdc42dd29b53",
                            Content = "Відповідь 88",
                            QuestionId = "cb1f165b-2950-481b-91a2-89174acad2b8"
                        },
                        new
                        {
                            Id = "5b2d53b9-0215-4b80-9b41-4e11b9ed492b",
                            Content = "Відповідь 72",
                            QuestionId = "cb1f165b-2950-481b-91a2-89174acad2b8"
                        },
                        new
                        {
                            Id = "838689c3-d16d-4d3f-8dae-5208145b21a7",
                            Content = "Відповідь 49",
                            QuestionId = "08b47494-defb-4bf6-b5f7-d861d0f01e59"
                        },
                        new
                        {
                            Id = "60e83f56-8c87-4947-9dfc-bfddd3ee6b87",
                            Content = "Відповідь 53",
                            QuestionId = "08b47494-defb-4bf6-b5f7-d861d0f01e59"
                        },
                        new
                        {
                            Id = "b47fd5b3-3717-4c45-801b-5843699066d5",
                            Content = "Відповідь 35",
                            QuestionId = "08b47494-defb-4bf6-b5f7-d861d0f01e59"
                        },
                        new
                        {
                            Id = "e4489d91-6fa4-43a2-8a84-fffa3199e8fd",
                            Content = "Відповідь 62",
                            QuestionId = "08b47494-defb-4bf6-b5f7-d861d0f01e59"
                        });
                });

            modelBuilder.Entity("opytuvannia_backend.Entities.Company", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("LogoSrc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("logo_src");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_companies");

                    b.ToTable("companies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "5046df65-b65e-4a6b-bb8a-e05c1b21f4e3",
                            LogoSrc = "https://silpo.ua/images/silpo_fb_share.png",
                            Name = "Сільпо"
                        },
                        new
                        {
                            Id = "75fcdb74-bee8-4441-bab0-7225a7553ea2",
                            LogoSrc = "https://cdn.metro-online.com/-/media/Project/MCW/RU_Metro/2021/join-us/Metro.png?rev=fe69769d14aa4105bc7e5731e32ebfc7&w=339&hash=783A0BB0789E586BB438C44B0778558A",
                            Name = "Metro"
                        },
                        new
                        {
                            Id = "57d591d7-b380-4763-8615-58231b984942",
                            LogoSrc = "https://allretail.ua/static/files/originals/2/85/30b01f786bd9a28d98e745247184f852.svg",
                            Name = "АТБ"
                        });
                });

            modelBuilder.Entity("opytuvannia_backend.Entities.Question", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("SurveyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("survey_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_questions");

                    b.HasIndex("SurveyId")
                        .HasDatabaseName("ix_questions_survey_id");

                    b.ToTable("questions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "6d3d0979-35c7-47e7-ad80-56b5fe36307b",
                            SurveyId = "36d380a6-7007-4928-9e00-ca3c9a1acf14",
                            Title = "Яке пиво ви купуєте найчастіше?"
                        },
                        new
                        {
                            Id = "4c6005ec-2113-45f8-a244-44b46fc41e71",
                            SurveyId = "36d380a6-7007-4928-9e00-ca3c9a1acf14",
                            Title = "Чи спробували ви нові сорти пива в нашому магазині?"
                        },
                        new
                        {
                            Id = "ab44fa3d-7ab9-41e2-9592-9ea7b99bf39b",
                            SurveyId = "36d380a6-7007-4928-9e00-ca3c9a1acf14",
                            Title = "Які характеристики пива важливі для вас?"
                        },
                        new
                        {
                            Id = "488e1580-2be8-4224-a479-035586148414",
                            SurveyId = "36d380a6-7007-4928-9e00-ca3c9a1acf14",
                            Title = "Як часто ви купуєте пиво в наших магазинах?"
                        },
                        new
                        {
                            Id = "482e42f4-f116-4b47-b0ae-10b70354755d",
                            SurveyId = "3828d7fc-7b50-4da6-8884-599db176a644",
                            Title = "Який продукт ви купуєте найчастіше в Metro?"
                        },
                        new
                        {
                            Id = "c82ae074-05e3-4b6f-8789-e951720658a0",
                            SurveyId = "3828d7fc-7b50-4da6-8884-599db176a644",
                            Title = "Чи задоволені ви асортиментом товарів у наших магазинах?"
                        },
                        new
                        {
                            Id = "5aa48f79-3caa-4536-ab92-6675a5ce19cc",
                            SurveyId = "3828d7fc-7b50-4da6-8884-599db176a644",
                            Title = "Які характеристики товарів важливі для вас при покупці?"
                        },
                        new
                        {
                            Id = "81638814-b787-486a-a9c9-610b8a16d3e1",
                            SurveyId = "3828d7fc-7b50-4da6-8884-599db176a644",
                            Title = "Як часто ви відвідуєте наші магазини?"
                        },
                        new
                        {
                            Id = "2fec5013-2680-43a6-8621-40d14ec904c0",
                            SurveyId = "46cdf134-5d3b-4dfb-9dfb-039681eb932f",
                            Title = "Як часто ви здійснюєте покупки в АТБ?"
                        },
                        new
                        {
                            Id = "2d6da8e2-dc0b-47e7-962b-b8cd3997eba5",
                            SurveyId = "46cdf134-5d3b-4dfb-9dfb-039681eb932f",
                            Title = "Які товари ви найчастіше купуєте в наших магазинах?"
                        },
                        new
                        {
                            Id = "d504962b-d5ef-4d58-af58-606a2c852610",
                            SurveyId = "46cdf134-5d3b-4dfb-9dfb-039681eb932f",
                            Title = "Чи задоволені ви якістю обслуговування у наших магазинах?"
                        },
                        new
                        {
                            Id = "9dca22e2-4bd9-4a82-882a-f19835c95118",
                            SurveyId = "46cdf134-5d3b-4dfb-9dfb-039681eb932f",
                            Title = "Чи вважаєте ви наші ціни конкурентоспроможними?"
                        },
                        new
                        {
                            Id = "c085cd1d-4894-43f8-b383-d17371636f1c",
                            SurveyId = "51fb15c3-a702-41a6-8653-40b1cbd5e628",
                            Title = "Як ви оцінюєте чистоту наших магазинів?"
                        },
                        new
                        {
                            Id = "15e8db4e-bb53-4164-8ac9-0e1e995d2e1f",
                            SurveyId = "51fb15c3-a702-41a6-8653-40b1cbd5e628",
                            Title = "Чи допомагає вам персонал з пошуком товарів?"
                        },
                        new
                        {
                            Id = "cb1f165b-2950-481b-91a2-89174acad2b8",
                            SurveyId = "51fb15c3-a702-41a6-8653-40b1cbd5e628",
                            Title = "Чи вважаєте ви, що у нас завжди є необхідні товари?"
                        },
                        new
                        {
                            Id = "08b47494-defb-4bf6-b5f7-d861d0f01e59",
                            SurveyId = "51fb15c3-a702-41a6-8653-40b1cbd5e628",
                            Title = "Чи радите ви своїм знайомим відвідувати магазини АТБ?"
                        });
                });

            modelBuilder.Entity("opytuvannia_backend.Entities.Respondent", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birth_date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("Gender")
                        .HasColumnType("character varying(10)")
                        .HasColumnName("gender");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.HasKey("Id")
                        .HasName("pk_respondents");

                    b.ToTable("respondents", (string)null);
                });

            modelBuilder.Entity("opytuvannia_backend.Entities.RespondentReward", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("RespondentId")
                        .IsRequired()
                        .HasColumnType("character varying(36)")
                        .HasColumnName("respondent_id");

                    b.Property<string>("RewardId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reward_id");

                    b.HasKey("Id")
                        .HasName("pk_respondent_reward");

                    b.HasIndex("RespondentId")
                        .HasDatabaseName("ix_respondent_reward_respondent_id");

                    b.ToTable("respondent_reward", (string)null);
                });

            modelBuilder.Entity("opytuvannia_backend.Entities.RespondentSurvey", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CompletionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completion_date");

                    b.Property<string>("RespondentId")
                        .IsRequired()
                        .HasColumnType("character varying(36)")
                        .HasColumnName("respondent_id");

                    b.Property<string>("SurveyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("survey_id");

                    b.HasKey("Id")
                        .HasName("pk_respondent_surveys");

                    b.HasIndex("RespondentId")
                        .HasDatabaseName("ix_respondent_surveys_respondent_id");

                    b.HasIndex("SurveyId")
                        .HasDatabaseName("ix_respondent_surveys_survey_id");

                    b.ToTable("respondent_surveys", (string)null);
                });

            modelBuilder.Entity("opytuvannia_backend.Entities.RespondentSurveyAnswer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AnswerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("answer_id");

                    b.Property<string>("QuestionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_id");

                    b.Property<string>("RespondentSurveyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("respondent_survey_id");

                    b.HasKey("Id")
                        .HasName("pk_respondent_survey_answers");

                    b.HasIndex("AnswerId")
                        .HasDatabaseName("ix_respondent_survey_answers_answer_id");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_respondent_survey_answers_question_id");

                    b.HasIndex("RespondentSurveyId")
                        .HasDatabaseName("ix_respondent_survey_answers_respondent_survey_id");

                    b.ToTable("respondent_survey_answers", (string)null);
                });

            modelBuilder.Entity("opytuvannia_backend.Entities.Reward", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.HasKey("Id")
                        .HasName("pk_rewards");

                    b.ToTable("rewards", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "7b128dcf-8520-4c18-ac6c-75e6bd1cb349",
                            Content = "Промокод -50% на чернігівське титан zxcqw-e13371000-7wwww"
                        },
                        new
                        {
                            Id = "3ff1ce43-d650-4ea8-a409-cfe4c6170988",
                            Content = "+100 грн"
                        },
                        new
                        {
                            Id = "3e4c4aeb-80c4-4120-8885-b6e566ee368f",
                            Content = "Знижка 10% на наступну покупку"
                        },
                        new
                        {
                            Id = "9d787398-4942-42e2-9ed1-c56f96326644",
                            Content = "Безкоштовна доставка при наступному замовленні"
                        });
                });

            modelBuilder.Entity("opytuvannia_backend.Entities.Survey", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("RewardId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reward_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_surveys");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_surveys_company_id");

                    b.HasIndex("RewardId")
                        .HasDatabaseName("ix_surveys_reward_id");

                    b.ToTable("surveys", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "36d380a6-7007-4928-9e00-ca3c9a1acf14",
                            CompanyId = "5046df65-b65e-4a6b-bb8a-e05c1b21f4e3",
                            Description = "Опитування про ваші уподобання щодо пива",
                            RewardId = "7b128dcf-8520-4c18-ac6c-75e6bd1cb349",
                            Title = "Споживання пива"
                        },
                        new
                        {
                            Id = "3828d7fc-7b50-4da6-8884-599db176a644",
                            CompanyId = "75fcdb74-bee8-4441-bab0-7225a7553ea2",
                            Description = "Допоможіть нам визначити найпопулярніший продукт в Metro",
                            RewardId = "3ff1ce43-d650-4ea8-a409-cfe4c6170988",
                            Title = "Найкращий продукт"
                        },
                        new
                        {
                            Id = "46cdf134-5d3b-4dfb-9dfb-039681eb932f",
                            CompanyId = "57d591d7-b380-4763-8615-58231b984942",
                            Description = "Щоб покращити обслуговування, просимо вас взяти участь в нашому опитуванні",
                            RewardId = "3e4c4aeb-80c4-4120-8885-b6e566ee368f",
                            Title = "Ваші покупки в АТБ"
                        },
                        new
                        {
                            Id = "51fb15c3-a702-41a6-8653-40b1cbd5e628",
                            CompanyId = "57d591d7-b380-4763-8615-58231b984942",
                            Description = "Оцініть якість обслуговування в наших магазинах",
                            RewardId = "3e4c4aeb-80c4-4120-8885-b6e566ee368f",
                            Title = "Якість обслуговування"
                        });
                });

            modelBuilder.Entity("opytuvannia_backend.Entities.Answer", b =>
                {
                    b.HasOne("opytuvannia_backend.Entities.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_answers_questions_question_id");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("opytuvannia_backend.Entities.Question", b =>
                {
                    b.HasOne("opytuvannia_backend.Entities.Survey", "Survey")
                        .WithMany("Questions")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_questions_surveys_survey_id");

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("opytuvannia_backend.Entities.RespondentReward", b =>
                {
                    b.HasOne("opytuvannia_backend.Entities.Respondent", null)
                        .WithMany("Rewards")
                        .HasForeignKey("RespondentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_respondent_reward_respondents_respondent_id");
                });

            modelBuilder.Entity("opytuvannia_backend.Entities.RespondentSurvey", b =>
                {
                    b.HasOne("opytuvannia_backend.Entities.Respondent", "Respondent")
                        .WithMany("CompletedSurveys")
                        .HasForeignKey("RespondentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_respondent_surveys_respondents_respondent_id");

                    b.HasOne("opytuvannia_backend.Entities.Survey", "Survey")
                        .WithMany()
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_respondent_surveys_surveys_survey_id");

                    b.Navigation("Respondent");

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("opytuvannia_backend.Entities.RespondentSurveyAnswer", b =>
                {
                    b.HasOne("opytuvannia_backend.Entities.Answer", "Answer")
                        .WithMany()
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_respondent_survey_answers_answers_answer_id");

                    b.HasOne("opytuvannia_backend.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_respondent_survey_answers_questions_question_id");

                    b.HasOne("opytuvannia_backend.Entities.RespondentSurvey", "RespondentSurvey")
                        .WithMany("Answers")
                        .HasForeignKey("RespondentSurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_respondent_survey_answers_respondent_surveys_respondent_sur");

                    b.Navigation("Answer");

                    b.Navigation("Question");

                    b.Navigation("RespondentSurvey");
                });

            modelBuilder.Entity("opytuvannia_backend.Entities.Survey", b =>
                {
                    b.HasOne("opytuvannia_backend.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_surveys_companies_company_id");

                    b.HasOne("opytuvannia_backend.Entities.Reward", "Reward")
                        .WithMany()
                        .HasForeignKey("RewardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_surveys_rewards_reward_id");

                    b.Navigation("Company");

                    b.Navigation("Reward");
                });

            modelBuilder.Entity("opytuvannia_backend.Entities.Question", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("opytuvannia_backend.Entities.Respondent", b =>
                {
                    b.Navigation("CompletedSurveys");

                    b.Navigation("Rewards");
                });

            modelBuilder.Entity("opytuvannia_backend.Entities.RespondentSurvey", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("opytuvannia_backend.Entities.Survey", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
